import { imageRefs, type Stack } from "./stack.js";
import type { GeneratedSecrets } from "./secrets.js";

export interface InstallConfig {
  mode: "localhost" | "domain";
  dir: string;
  projectName: string;
  stack: Stack;
  secrets: GeneratedSecrets;
  adminEmail: string;
  llm: {
    providerId: string;
    baseUrl: string;
    apiKey: string;
    chatModel: string;
    embeddingModel: string;
    embeddingDimension: number;
    embeddingSendDimensions: boolean;
    maxContext?: number;
    embeddingBaseUrl?: string;
    embeddingApiKey?: string;
  };
  ports: { app: number; chat: number; api: number; neo4jHttp: number; neo4jBolt: number };
  domains?: { app: string; chat: string; acmeEmail: string };
  smtp?: { host: string; port: number; user?: string; pass?: string; secure: boolean; from: string };
  errorReporting: boolean;
  advanced?: {
    graphExtractionModel?: string;
    visionModel?: string;
    enableReranking?: boolean;
    neo4jMemLimit?: string;
    batchConcurrency?: number;
  };
}

/** Every ${VAR:?} the released compose enforces. */
export const REQUIRED_VARS = [
  "CORTEX_BACKEND_IMAGE",
  "CORTEX_FRONTEND_IMAGE",
  "CORTEX_CHAT_IMAGE",
  "NEO4J_PASSWORD",
  "OPENAI_API_KEY",
  "ADMIN_PASSWORD",
  "ADMIN_API_KEY",
  "SESSION_SECRET",
  "CHAT_APP_ENCRYPTION_KEY",
  "APP_DOMAIN",
  "CHAT_DOMAIN",
  "ACME_EMAIL",
] as const;

const COMPOSE_FILES = {
  localhost: "docker-compose.yml:docker-compose.ports.yml",
  domain: "docker-compose.yml:docker-compose.caddy.yml",
} as const;

export function renderEnv(cfg: InstallConfig): string {
  const img = imageRefs(cfg.stack);
  const L: string[] = [];
  const put = (k: string, v: string | number) => L.push(`${k}=${v}`);
  const section = (title: string) => {
    L.push("", `# --- ${title} ${"-".repeat(Math.max(1, 68 - title.length))}`);
  };

  L.push(
    "# Cortex self-host configuration.",
    "#",
    "# Generated by `npx @mocaos/cortex`. This is the ONLY file the installer",
    "# authors — the compose files are release artifacts and are never edited,",
    "# so your changes here survive `cortex update`.",
    "#",
    "# Local compose changes belong in docker-compose.override.yml, which",
    "# Compose merges automatically and the installer never touches.",
    "#",
    "# NEXT_PUBLIC_API_URL is deliberately never set here, in any mode, and you",
    "# should not add it yourself. The browser calls same-origin /api/* and the",
    "# frontend proxies to the backend server-side; setting this var breaks",
    "# that same-origin routing and breaks the single published frontend image",
    "# working across every install (localhost and every domain alike).",
    "#",
    "# Keep this file at mode 600: it holds every secret."
  );

  section("Mode");
  put("COMPOSE_FILE", COMPOSE_FILES[cfg.mode]);
  put("COMPOSE_PROJECT_NAME", cfg.projectName);

  section("Images (pinned from stack.json)");
  put("CORTEX_BACKEND_IMAGE", img.backend);
  put("CORTEX_FRONTEND_IMAGE", img.frontend);
  put("CORTEX_CHAT_IMAGE", img.chat);
  put("NEO4J_VERSION", cfg.stack.components.neo4j);
  put("CADDY_VERSION", cfg.stack.components.caddy);

  if (cfg.mode === "localhost") {
    section("Localhost mode");
    L.push("# Loopback only — 0.0.0.0 would expose Neo4j and the API to the network.");
    put("BIND_ADDR", "127.0.0.1");
    put("APP_PORT", cfg.ports.app);
    put("CHAT_PORT", cfg.ports.chat);
    put("API_PORT", cfg.ports.api);
    put("NEO4J_HTTP_PORT", cfg.ports.neo4jHttp);
    put("NEO4J_BOLT_PORT", cfg.ports.neo4jBolt);
    L.push(
      "",
      "# SESSION_COOKIE_SECURE is deliberately absent. The ports overlay sets it",
      "# false for plain HTTP; domain mode leaves it unset so the app defaults to",
      "# Secure. Setting it here would apply to both modes and strip Secure from",
      "# the admin session cookie on a public HTTPS site."
    );
  } else {
    const d = cfg.domains!;
    section("Public domain mode");
    L.push("# Both domains must already have A records pointing at this host.");
    put("APP_DOMAIN", d.app);
    put("CHAT_DOMAIN", d.chat);
    put("ACME_EMAIL", d.acmeEmail);
    put("CHAT_BASE_URL", `https://${d.chat}`);
    put("CORS_ALLOWED_ORIGINS", `https://${d.app},https://${d.chat}`);
  }

  section("Secrets");
  put("NEO4J_PASSWORD", cfg.secrets.neo4jPassword);
  put("ADMIN_EMAIL", cfg.adminEmail);
  put("ADMIN_PASSWORD", cfg.secrets.adminPassword);
  put("ADMIN_API_KEY", cfg.secrets.adminApiKey);
  put("SESSION_SECRET", cfg.secrets.sessionSecret);
  put("CHAT_APP_ENCRYPTION_KEY", cfg.secrets.chatEncryptionKey);

  section("LLM");
  put("OPENAI_API_KEY", cfg.llm.apiKey);
  put("OPENAI_API_BASE", cfg.llm.baseUrl);
  put("OPENAI_MODEL", cfg.llm.chatModel);
  if (cfg.llm.maxContext) put("OPENAI_MAX_CONTEXT", cfg.llm.maxContext);

  section("Embeddings");
  L.push("# EMBEDDING_DIMENSION is baked into the Neo4j vector index on first use.");
  L.push("# Changing it later forces a full re-embed of the corpus.");
  put("USE_OPENAI_EMBEDDINGS", "true");
  put("EMBEDDING_MODEL", cfg.llm.embeddingModel);
  put("EMBEDDING_DIMENSION", cfg.llm.embeddingDimension);
  put("EMBEDDING_SEND_DIMENSIONS", String(cfg.llm.embeddingSendDimensions));
  if (cfg.llm.embeddingBaseUrl) put("EMBEDDING_API_BASE", cfg.llm.embeddingBaseUrl);
  if (cfg.llm.embeddingApiKey) put("EMBEDDING_API_KEY", cfg.llm.embeddingApiKey);

  if (cfg.advanced) {
    section("Model overrides");
    const a = cfg.advanced;
    if (a.graphExtractionModel) put("GRAPH_EXTRACTION_MODEL", a.graphExtractionModel);
    if (a.visionModel) put("VISION_MODEL", a.visionModel);
    if (a.enableReranking !== undefined) put("ENABLE_RERANKING", String(a.enableReranking));
    if (a.neo4jMemLimit) put("CORTEX_NEO4J_MEM_LIMIT", a.neo4jMemLimit);
    if (a.batchConcurrency !== undefined) put("BATCH_PROCESSING_CONCURRENCY", a.batchConcurrency);
  }

  section("Error tracking");
  L.push(
    "# Off by default. Your stack traces stay on your machine unless you set a",
    "# DSN pointing at your own GlitchTip/Sentry."
  );
  put("SENTRY_DSN_BACKEND", "");
  put("SENTRY_DSN_FRONTEND", "");
  put("CHAT_SENTRY_DISABLED", cfg.errorReporting ? "0" : "1");

  if (cfg.smtp) {
    section("Chat email");
    put("SMTP_HOST", cfg.smtp.host);
    put("SMTP_PORT", cfg.smtp.port);
    if (cfg.smtp.user) put("SMTP_USER", cfg.smtp.user);
    if (cfg.smtp.pass) put("SMTP_PASS", cfg.smtp.pass);
    put("SMTP_SECURE", String(cfg.smtp.secure));
    put("SMTP_FROM", cfg.smtp.from);
  }

  return `${L.join("\n")}\n`;
}
